/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HelloZubinInterface extends Interface {
  getFunction(nameOrSignature: "sayHello"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "helloSir"): EventFragment;

  encodeFunctionData(functionFragment: "sayHello", values: [string]): string;

  decodeFunctionResult(functionFragment: "sayHello", data: BytesLike): Result;
}

export namespace helloSirEvent {
  export type InputTuple = [name: string, caller: AddressLike];
  export type OutputTuple = [name: string, caller: string];
  export interface OutputObject {
    name: string;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HelloZubin extends BaseContract {
  connect(runner?: ContractRunner | null): HelloZubin;
  waitForDeployment(): Promise<this>;

  interface: HelloZubinInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sayHello: TypedContractMethod<[name: string], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sayHello"
  ): TypedContractMethod<[name: string], [string], "nonpayable">;

  getEvent(
    key: "helloSir"
  ): TypedContractEvent<
    helloSirEvent.InputTuple,
    helloSirEvent.OutputTuple,
    helloSirEvent.OutputObject
  >;

  filters: {
    "helloSir(string,address)": TypedContractEvent<
      helloSirEvent.InputTuple,
      helloSirEvent.OutputTuple,
      helloSirEvent.OutputObject
    >;
    helloSir: TypedContractEvent<
      helloSirEvent.InputTuple,
      helloSirEvent.OutputTuple,
      helloSirEvent.OutputObject
    >;
  };
}
