/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloZubin } from "./HelloZubin";
export * as factories from "./factories";
export { HelloZubin__factory } from "./factories/HelloZubin__factory";
